export const TRAVEL_TO_LOCATION = 'TRAVEL_TO_LOCATION';
export const SELECT_SCENARIO = 'SELECT_SCENARIO';
export const START_CONVERSATION = 'START_CONVERSATION';
export const STOP_CONVERSATION = 'STOP_CONVERSATION';
export const INVESTIGATE_OBJECT = 'INVESTIGATE_OBJECT';
export const FIND_CLUE = 'FIND_CLUE';
export const ASK_QUESTION = 'ASK_QUESTION';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';